### ISSUE TITLE
action.call fails with gmediarender

### ISSUE THREAD

**Issue by eadmaster** [fboender/pyupnpclient#1]
i am trying to use this library to read the current playing song title in gmediarender:
```

import upnpclient
server = upnpclient.Server('http://192.168.42.79:49494/description.xml')
action = server.find_action('GetMediaInfo')
response = action.call(InstanceID=0)
print response

```

but it fails with this exception:

```
Traceback (most recent call last):
  File "action_call2.py", line 18, in <module>
    response = action.call(InstanceID=0)
  File "/tmp/r/pyupnpclient-master/pyupnpclient-master/examples/upnpclient.py", line 513, in call
    soap_response = soap_client.call(self.name, args)
  File "/tmp/r/pyupnpclient-master/pyupnpclient-master/examples/upnpclient.py", line 626, in call
    int(_XMLGetNodeText(soap_error_xml.getElementsByTagName('errorCode')[0])),
IndexError: list index out of range
```

**Comment by fboender** [comment]
Can you send me an example of that description.xml?

**Comment by eadmaster** [comment]
description.xml:
```
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<presentationURL></presentationURL>
<friendlyName>&quot;OrangePi&quot;</friendlyName>
<manufacturer>Ivo Clarysse, Henner Zeller</manufacturer>
<manufacturerURL>http://github.com/hzeller/gmrender-resurrect</manufacturerURL>
<modelDescription>gmediarender 0.0.7-git</modelDescription>
<modelName>gmediarender</modelName>
<modelNumber>0.0.7-git</modelNumber>
<modelURL>http://github.com/hzeller/gmrender-resurrect</modelURL>
<UDN>uuid:&quot;cac2d4c1f05a74a133609cafa78b1e39&quot;</UDN>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>64</width>
<height>64</height>
<depth>24</depth>
<url>/upnp/grender-64x64.png</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>128</width>
<height>128</height>
<depth>24</depth>
<url>/upnp/grender-128x128.png</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
<SCPDURL>/upnp/rendertransportSCPD.xml</SCPDURL>
<controlURL>/upnp/control/rendertransport1</controlURL>
<eventSubURL>/upnp/event/rendertransport1</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<SCPDURL>/upnp/renderconnmgrSCPD.xml</SCPDURL>
<controlURL>/upnp/control/renderconnmgr1</controlURL>
<eventSubURL>/upnp/event/renderconnmgr1</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
<SCPDURL>/upnp/rendercontrolSCPD.xml</SCPDURL>
<controlURL>/upnp/control/rendercontrol1</controlURL>
<eventSubURL>/upnp/event/rendercontrol1</eventSubURL>
</service>
</serviceList>
</device>
<URLBase>http://192.168.42.79:49494/</URLBase>
</root>

```

**Comment by fboender** [comment]
HI Andrea!

It seems I've got very little time to maintain this project. Another developer has taken the time to implement a new project based on this code and has brought it up to standards for production use. You can find the project here: https://github.com/flyte/upnpclient

Since I'm not really maintaining this project anymore (as it's mostly example code for a blog post I wrote), I'm going to close this bug report. Sorry I didn't have the time to fix it for you! I hope Flyte's version works better for you.

Regards
